name: Newman Run

on:
  push:
    branches:
    - main

jobs:
  newman-api-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master Branch 
        uses: actions/checkout@master

      - name: Testing API Using Matt-Ball   
        uses: matt-ball/newman-action@master
        with:
          collection: First Collection.postman_collection.json
          environment: New Environment.postman_environment.json

      - name: Testing API with Iterations
        id: run-newman
        uses: anthonyvscode/newman-action@v1
        with:
          apiKey: ${{ secrets.newman17november }}
          iterationCount: 2
          iterationData: First Collection.postman_collection.json
          collection: First Collection.postman_collection.json

      - name: Outpute Summary
        run: echo ${{ steps.run-newman.outputs.summary }}

      - name: Outpute Summary_Full
        run: echo ${{ steps.run-newman.outputs.summary_full }}
